//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixV3._0Client.ProductServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private int QuantityField;
        
        private decimal PriceField;
        
        private decimal DiscountField;
        
        private int SupplierIdField;
        
        private System.DateTime CreatedAtField;
        
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name itemName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.AddProductResponse AddProduct(TechFixV3._0Client.ProductServiceReference.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.AddProductResponse> AddProductAsync(TechFixV3._0Client.ProductServiceReference.AddProductRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.DeleteProductResponse DeleteProduct(TechFixV3._0Client.ProductServiceReference.DeleteProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.DeleteProductResponse> DeleteProductAsync(TechFixV3._0Client.ProductServiceReference.DeleteProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.GetProductsResponse GetProducts(TechFixV3._0Client.ProductServiceReference.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsResponse> GetProductsAsync(TechFixV3._0Client.ProductServiceReference.GetProductsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductsBySupplierIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsBySupplierId", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse GetProductsBySupplierId(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsBySupplierId", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse> GetProductsBySupplierIdAsync(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse GetProductById(TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse> GetProductByIdAsync(TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest request);
        
        // CODEGEN: Generating message contract since element name itemName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        TechFixV3._0Client.ProductServiceReference.UpdateProductResponse UpdateProduct(TechFixV3._0Client.ProductServiceReference.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.UpdateProductResponse> UpdateProductAsync(TechFixV3._0Client.ProductServiceReference.UpdateProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(TechFixV3._0Client.ProductServiceReference.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal discount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int supplierId;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            this.itemName = itemName;
            this.quantity = quantity;
            this.price = price;
            this.discount = discount;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(TechFixV3._0Client.ProductServiceReference.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddProductResult;
        
        public AddProductResponseBody() {
        }
        
        public AddProductResponseBody(string AddProductResult) {
            this.AddProductResult = AddProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.DeleteProductRequestBody Body;
        
        public DeleteProductRequest() {
        }
        
        public DeleteProductRequest(TechFixV3._0Client.ProductServiceReference.DeleteProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public DeleteProductRequestBody() {
        }
        
        public DeleteProductRequestBody(int productId) {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.DeleteProductResponseBody Body;
        
        public DeleteProductResponse() {
        }
        
        public DeleteProductResponse(TechFixV3._0Client.ProductServiceReference.DeleteProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteProductResult;
        
        public DeleteProductResponseBody() {
        }
        
        public DeleteProductResponseBody(string DeleteProductResult) {
            this.DeleteProductResult = DeleteProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(TechFixV3._0Client.ProductServiceReference.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(TechFixV3._0Client.ProductServiceReference.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.ProductServiceReference.Product[] GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(TechFixV3._0Client.ProductServiceReference.Product[] GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsBySupplierIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsBySupplierId", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequestBody Body;
        
        public GetProductsBySupplierIdRequest() {
        }
        
        public GetProductsBySupplierIdRequest(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsBySupplierIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public GetProductsBySupplierIdRequestBody() {
        }
        
        public GetProductsBySupplierIdRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsBySupplierIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsBySupplierIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponseBody Body;
        
        public GetProductsBySupplierIdResponse() {
        }
        
        public GetProductsBySupplierIdResponse(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsBySupplierIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.ProductServiceReference.Product[] GetProductsBySupplierIdResult;
        
        public GetProductsBySupplierIdResponseBody() {
        }
        
        public GetProductsBySupplierIdResponseBody(TechFixV3._0Client.ProductServiceReference.Product[] GetProductsBySupplierIdResult) {
            this.GetProductsBySupplierIdResult = GetProductsBySupplierIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductById", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductByIdRequestBody Body;
        
        public GetProductByIdRequest() {
        }
        
        public GetProductByIdRequest(TechFixV3._0Client.ProductServiceReference.GetProductByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public GetProductByIdRequestBody() {
        }
        
        public GetProductByIdRequestBody(int productId) {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.GetProductByIdResponseBody Body;
        
        public GetProductByIdResponse() {
        }
        
        public GetProductByIdResponse(TechFixV3._0Client.ProductServiceReference.GetProductByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.ProductServiceReference.Product GetProductByIdResult;
        
        public GetProductByIdResponseBody() {
        }
        
        public GetProductByIdResponseBody(TechFixV3._0Client.ProductServiceReference.Product GetProductByIdResult) {
            this.GetProductByIdResult = GetProductByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(TechFixV3._0Client.ProductServiceReference.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string itemName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal discount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int supplierId;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(int productId, string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            this.productId = productId;
            this.itemName = itemName;
            this.quantity = quantity;
            this.price = price;
            this.discount = discount;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ProductServiceReference.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(TechFixV3._0Client.ProductServiceReference.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateProductResult;
        
        public UpdateProductResponseBody() {
        }
        
        public UpdateProductResponseBody(string UpdateProductResult) {
            this.UpdateProductResult = UpdateProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : TechFixV3._0Client.ProductServiceReference.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<TechFixV3._0Client.ProductServiceReference.ProductServiceSoap>, TechFixV3._0Client.ProductServiceReference.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.AddProductResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.AddProduct(TechFixV3._0Client.ProductServiceReference.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public string AddProduct(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.ProductServiceReference.AddProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.AddProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.AddProductRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.ProductServiceReference.AddProductResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).AddProduct(inValue);
            return retVal.Body.AddProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.AddProductResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.AddProductAsync(TechFixV3._0Client.ProductServiceReference.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.AddProductResponse> AddProductAsync(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.ProductServiceReference.AddProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.AddProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.AddProductRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.DeleteProductResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.DeleteProduct(TechFixV3._0Client.ProductServiceReference.DeleteProductRequest request) {
            return base.Channel.DeleteProduct(request);
        }
        
        public string DeleteProduct(int productId) {
            TechFixV3._0Client.ProductServiceReference.DeleteProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.DeleteProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.DeleteProductRequestBody();
            inValue.Body.productId = productId;
            TechFixV3._0Client.ProductServiceReference.DeleteProductResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).DeleteProduct(inValue);
            return retVal.Body.DeleteProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.DeleteProductResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.DeleteProductAsync(TechFixV3._0Client.ProductServiceReference.DeleteProductRequest request) {
            return base.Channel.DeleteProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.DeleteProductResponse> DeleteProductAsync(int productId) {
            TechFixV3._0Client.ProductServiceReference.DeleteProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.DeleteProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.DeleteProductRequestBody();
            inValue.Body.productId = productId;
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).DeleteProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.GetProductsResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProducts(TechFixV3._0Client.ProductServiceReference.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public TechFixV3._0Client.ProductServiceReference.Product[] GetProducts() {
            TechFixV3._0Client.ProductServiceReference.GetProductsRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductsRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductsRequestBody();
            TechFixV3._0Client.ProductServiceReference.GetProductsResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProductsAsync(TechFixV3._0Client.ProductServiceReference.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsResponse> GetProductsAsync() {
            TechFixV3._0Client.ProductServiceReference.GetProductsRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductsRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductsRequestBody();
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProductsBySupplierId(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest request) {
            return base.Channel.GetProductsBySupplierId(request);
        }
        
        public TechFixV3._0Client.ProductServiceReference.Product[] GetProductsBySupplierId(int supplierId) {
            TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProductsBySupplierId(inValue);
            return retVal.Body.GetProductsBySupplierIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProductsBySupplierIdAsync(TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest request) {
            return base.Channel.GetProductsBySupplierIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdResponse> GetProductsBySupplierIdAsync(int supplierId) {
            TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductsBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProductsBySupplierIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProductById(TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest request) {
            return base.Channel.GetProductById(request);
        }
        
        public TechFixV3._0Client.ProductServiceReference.Product GetProductById(int productId) {
            TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductByIdRequestBody();
            inValue.Body.productId = productId;
            TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProductById(inValue);
            return retVal.Body.GetProductByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.GetProductByIdAsync(TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest request) {
            return base.Channel.GetProductByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.GetProductByIdResponse> GetProductByIdAsync(int productId) {
            TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest inValue = new TechFixV3._0Client.ProductServiceReference.GetProductByIdRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.GetProductByIdRequestBody();
            inValue.Body.productId = productId;
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).GetProductByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ProductServiceReference.UpdateProductResponse TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.UpdateProduct(TechFixV3._0Client.ProductServiceReference.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public string UpdateProduct(int productId, string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.ProductServiceReference.UpdateProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.UpdateProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.ProductServiceReference.UpdateProductResponse retVal = ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).UpdateProduct(inValue);
            return retVal.Body.UpdateProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.UpdateProductResponse> TechFixV3._0Client.ProductServiceReference.ProductServiceSoap.UpdateProductAsync(TechFixV3._0Client.ProductServiceReference.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ProductServiceReference.UpdateProductResponse> UpdateProductAsync(int productId, string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.ProductServiceReference.UpdateProductRequest inValue = new TechFixV3._0Client.ProductServiceReference.UpdateProductRequest();
            inValue.Body = new TechFixV3._0Client.ProductServiceReference.UpdateProductRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.ProductServiceReference.ProductServiceSoap)(this)).UpdateProductAsync(inValue);
        }
    }
}
