//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixV3._0Client.ReportsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesReportItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SalesReportItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private int StockQuantityField;
        
        private int SoldQuantityField;
        
        private decimal TotalSalesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StockQuantity {
            get {
                return this.StockQuantityField;
            }
            set {
                if ((this.StockQuantityField.Equals(value) != true)) {
                    this.StockQuantityField = value;
                    this.RaisePropertyChanged("StockQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int SoldQuantity {
            get {
                return this.SoldQuantityField;
            }
            set {
                if ((this.SoldQuantityField.Equals(value) != true)) {
                    this.SoldQuantityField = value;
                    this.RaisePropertyChanged("SoldQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal TotalSales {
            get {
                return this.TotalSalesField;
            }
            set {
                if ((this.TotalSalesField.Equals(value) != true)) {
                    this.TotalSalesField = value;
                    this.RaisePropertyChanged("TotalSales");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportsServiceReference.ReportsServiceSoap")]
    public interface ReportsServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetSalesReportBySupplierIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSalesReportBySupplierId", ReplyAction="*")]
        TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse GetSalesReportBySupplierId(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSalesReportBySupplierId", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse> GetSalesReportBySupplierIdAsync(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalesReportBySupplierIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSalesReportBySupplierId", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequestBody Body;
        
        public GetSalesReportBySupplierIdRequest() {
        }
        
        public GetSalesReportBySupplierIdRequest(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalesReportBySupplierIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public GetSalesReportBySupplierIdRequestBody() {
        }
        
        public GetSalesReportBySupplierIdRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSalesReportBySupplierIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSalesReportBySupplierIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponseBody Body;
        
        public GetSalesReportBySupplierIdResponse() {
        }
        
        public GetSalesReportBySupplierIdResponse(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSalesReportBySupplierIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.ReportsServiceReference.SalesReportItem[] GetSalesReportBySupplierIdResult;
        
        public GetSalesReportBySupplierIdResponseBody() {
        }
        
        public GetSalesReportBySupplierIdResponseBody(TechFixV3._0Client.ReportsServiceReference.SalesReportItem[] GetSalesReportBySupplierIdResult) {
            this.GetSalesReportBySupplierIdResult = GetSalesReportBySupplierIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportsServiceSoapChannel : TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsServiceSoapClient : System.ServiceModel.ClientBase<TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap>, TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap {
        
        public ReportsServiceSoapClient() {
        }
        
        public ReportsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap.GetSalesReportBySupplierId(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest request) {
            return base.Channel.GetSalesReportBySupplierId(request);
        }
        
        public TechFixV3._0Client.ReportsServiceReference.SalesReportItem[] GetSalesReportBySupplierId(int supplierId) {
            TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest inValue = new TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse retVal = ((TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap)(this)).GetSalesReportBySupplierId(inValue);
            return retVal.Body.GetSalesReportBySupplierIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse> TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap.GetSalesReportBySupplierIdAsync(TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest request) {
            return base.Channel.GetSalesReportBySupplierIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdResponse> GetSalesReportBySupplierIdAsync(int supplierId) {
            TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest inValue = new TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.ReportsServiceReference.GetSalesReportBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.ReportsServiceReference.ReportsServiceSoap)(this)).GetSalesReportBySupplierIdAsync(inValue);
        }
    }
}
