//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixV3._0Client.InventoryServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventoryItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InventoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private int QuantityField;
        
        private decimal PriceField;
        
        private decimal DiscountField;
        
        private int SupplierIdField;
        
        private System.DateTime CreatedAtField;
        
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((this.DiscountField.Equals(value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventoryServiceReference.InventoryServiceSoap")]
    public interface InventoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventory", ReplyAction="*")]
        TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse GetInventory(TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse> GetInventoryAsync(TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetInventoryByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryById", ReplyAction="*")]
        TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse GetInventoryById(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryById", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse> GetInventoryByIdAsync(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest request);
        
        // CODEGEN: Generating message contract since element name UpdateInventoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse UpdateInventory(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse> UpdateInventoryAsync(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name itemName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInventoryItem", ReplyAction="*")]
        TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse AddInventoryItem(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddInventoryItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse> AddInventoryItemAsync(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteInventoryItemResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventoryItem", ReplyAction="*")]
        TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse DeleteInventoryItem(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteInventoryItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse> DeleteInventoryItemAsync(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventory", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.GetInventoryRequestBody Body;
        
        public GetInventoryRequest() {
        }
        
        public GetInventoryRequest(TechFixV3._0Client.InventoryServiceReference.GetInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInventoryRequestBody {
        
        public GetInventoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.GetInventoryResponseBody Body;
        
        public GetInventoryResponse() {
        }
        
        public GetInventoryResponse(TechFixV3._0Client.InventoryServiceReference.GetInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.InventoryItem[] GetInventoryResult;
        
        public GetInventoryResponseBody() {
        }
        
        public GetInventoryResponseBody(TechFixV3._0Client.InventoryServiceReference.InventoryItem[] GetInventoryResult) {
            this.GetInventoryResult = GetInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryById", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequestBody Body;
        
        public GetInventoryByIdRequest() {
        }
        
        public GetInventoryByIdRequest(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInventoryByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemId;
        
        public GetInventoryByIdRequestBody() {
        }
        
        public GetInventoryByIdRequestBody(int itemId) {
            this.itemId = itemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInventoryByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInventoryByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponseBody Body;
        
        public GetInventoryByIdResponse() {
        }
        
        public GetInventoryByIdResponse(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInventoryByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.InventoryItem GetInventoryByIdResult;
        
        public GetInventoryByIdResponseBody() {
        }
        
        public GetInventoryByIdResponseBody(TechFixV3._0Client.InventoryServiceReference.InventoryItem GetInventoryByIdResult) {
            this.GetInventoryByIdResult = GetInventoryByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateInventory", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequestBody Body;
        
        public UpdateInventoryRequest() {
        }
        
        public UpdateInventoryRequest(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal discount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int supplierId;
        
        public UpdateInventoryRequestBody() {
        }
        
        public UpdateInventoryRequestBody(int itemId, int quantity, decimal price, decimal discount, int supplierId) {
            this.itemId = itemId;
            this.quantity = quantity;
            this.price = price;
            this.discount = discount;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateInventoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponseBody Body;
        
        public UpdateInventoryResponse() {
        }
        
        public UpdateInventoryResponse(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateInventoryResult;
        
        public UpdateInventoryResponseBody() {
        }
        
        public UpdateInventoryResponseBody(string UpdateInventoryResult) {
            this.UpdateInventoryResult = UpdateInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInventoryItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInventoryItem", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequestBody Body;
        
        public AddInventoryItemRequest() {
        }
        
        public AddInventoryItemRequest(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddInventoryItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal price;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal discount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int supplierId;
        
        public AddInventoryItemRequestBody() {
        }
        
        public AddInventoryItemRequestBody(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            this.itemName = itemName;
            this.quantity = quantity;
            this.price = price;
            this.discount = discount;
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddInventoryItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddInventoryItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponseBody Body;
        
        public AddInventoryItemResponse() {
        }
        
        public AddInventoryItemResponse(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddInventoryItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddInventoryItemResult;
        
        public AddInventoryItemResponseBody() {
        }
        
        public AddInventoryItemResponseBody(string AddInventoryItemResult) {
            this.AddInventoryItemResult = AddInventoryItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteInventoryItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteInventoryItem", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequestBody Body;
        
        public DeleteInventoryItemRequest() {
        }
        
        public DeleteInventoryItemRequest(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteInventoryItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int itemId;
        
        public DeleteInventoryItemRequestBody() {
        }
        
        public DeleteInventoryItemRequestBody(int itemId) {
            this.itemId = itemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteInventoryItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteInventoryItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponseBody Body;
        
        public DeleteInventoryItemResponse() {
        }
        
        public DeleteInventoryItemResponse(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteInventoryItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteInventoryItemResult;
        
        public DeleteInventoryItemResponseBody() {
        }
        
        public DeleteInventoryItemResponseBody(string DeleteInventoryItemResult) {
            this.DeleteInventoryItemResult = DeleteInventoryItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryServiceSoapChannel : TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryServiceSoapClient : System.ServiceModel.ClientBase<TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap>, TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap {
        
        public InventoryServiceSoapClient() {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.GetInventory(TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest request) {
            return base.Channel.GetInventory(request);
        }
        
        public TechFixV3._0Client.InventoryServiceReference.InventoryItem[] GetInventory() {
            TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest inValue = new TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.GetInventoryRequestBody();
            TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse retVal = ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventory(inValue);
            return retVal.Body.GetInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse> TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.GetInventoryAsync(TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest request) {
            return base.Channel.GetInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryResponse> GetInventoryAsync() {
            TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest inValue = new TechFixV3._0Client.InventoryServiceReference.GetInventoryRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.GetInventoryRequestBody();
            return ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.GetInventoryById(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest request) {
            return base.Channel.GetInventoryById(request);
        }
        
        public TechFixV3._0Client.InventoryServiceReference.InventoryItem GetInventoryById(int itemId) {
            TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest inValue = new TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequestBody();
            inValue.Body.itemId = itemId;
            TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse retVal = ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventoryById(inValue);
            return retVal.Body.GetInventoryByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse> TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.GetInventoryByIdAsync(TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest request) {
            return base.Channel.GetInventoryByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdResponse> GetInventoryByIdAsync(int itemId) {
            TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest inValue = new TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.GetInventoryByIdRequestBody();
            inValue.Body.itemId = itemId;
            return ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).GetInventoryByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.UpdateInventory(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest request) {
            return base.Channel.UpdateInventory(request);
        }
        
        public string UpdateInventory(int itemId, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest inValue = new TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequestBody();
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse retVal = ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).UpdateInventory(inValue);
            return retVal.Body.UpdateInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse> TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.UpdateInventoryAsync(TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest request) {
            return base.Channel.UpdateInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.UpdateInventoryResponse> UpdateInventoryAsync(int itemId, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest inValue = new TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.UpdateInventoryRequestBody();
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).UpdateInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.AddInventoryItem(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest request) {
            return base.Channel.AddInventoryItem(request);
        }
        
        public string AddInventoryItem(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest inValue = new TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse retVal = ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).AddInventoryItem(inValue);
            return retVal.Body.AddInventoryItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse> TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.AddInventoryItemAsync(TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest request) {
            return base.Channel.AddInventoryItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.AddInventoryItemResponse> AddInventoryItemAsync(string itemName, int quantity, decimal price, decimal discount, int supplierId) {
            TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest inValue = new TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.AddInventoryItemRequestBody();
            inValue.Body.itemName = itemName;
            inValue.Body.quantity = quantity;
            inValue.Body.price = price;
            inValue.Body.discount = discount;
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).AddInventoryItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.DeleteInventoryItem(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest request) {
            return base.Channel.DeleteInventoryItem(request);
        }
        
        public string DeleteInventoryItem(int itemId) {
            TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest inValue = new TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequestBody();
            inValue.Body.itemId = itemId;
            TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse retVal = ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).DeleteInventoryItem(inValue);
            return retVal.Body.DeleteInventoryItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse> TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap.DeleteInventoryItemAsync(TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest request) {
            return base.Channel.DeleteInventoryItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemResponse> DeleteInventoryItemAsync(int itemId) {
            TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest inValue = new TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequest();
            inValue.Body = new TechFixV3._0Client.InventoryServiceReference.DeleteInventoryItemRequestBody();
            inValue.Body.itemId = itemId;
            return ((TechFixV3._0Client.InventoryServiceReference.InventoryServiceSoap)(this)).DeleteInventoryItemAsync(inValue);
        }
    }
}
