//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixV3._0Client.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime CreatedAtField;
        
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNumberField, value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.GetUsersResponse GetUsers(TechFixV3._0Client.UserServiceReference.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersResponse> GetUsersAsync(TechFixV3._0Client.UserServiceReference.GetUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.GetUserByIdResponse GetUserById(TechFixV3._0Client.UserServiceReference.GetUserByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserById", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUserByIdResponse> GetUserByIdAsync(TechFixV3._0Client.UserServiceReference.GetUserByIdRequest request);
        
        // CODEGEN: Generating message contract since element name role from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersByRole", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse GetUsersByRole(TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersByRole", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse> GetUsersByRoleAsync(TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.AddUserResponse AddUser(TechFixV3._0Client.UserServiceReference.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.AddUserResponse> AddUserAsync(TechFixV3._0Client.UserServiceReference.AddUserRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.UpdateUserResponse UpdateUser(TechFixV3._0Client.UserServiceReference.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.UpdateUserResponse> UpdateUserAsync(TechFixV3._0Client.UserServiceReference.UpdateUserRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        TechFixV3._0Client.UserServiceReference.DeleteUserResponse DeleteUser(TechFixV3._0Client.UserServiceReference.DeleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.DeleteUserResponse> DeleteUserAsync(TechFixV3._0Client.UserServiceReference.DeleteUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUsersRequestBody Body;
        
        public GetUsersRequest() {
        }
        
        public GetUsersRequest(TechFixV3._0Client.UserServiceReference.GetUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody {
        
        public GetUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUsersResponseBody Body;
        
        public GetUsersResponse() {
        }
        
        public GetUsersResponse(TechFixV3._0Client.UserServiceReference.GetUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.UserServiceReference.User[] GetUsersResult;
        
        public GetUsersResponseBody() {
        }
        
        public GetUsersResponseBody(TechFixV3._0Client.UserServiceReference.User[] GetUsersResult) {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserById", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUserByIdRequestBody Body;
        
        public GetUserByIdRequest() {
        }
        
        public GetUserByIdRequest(TechFixV3._0Client.UserServiceReference.GetUserByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserByIdRequestBody() {
        }
        
        public GetUserByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUserByIdResponseBody Body;
        
        public GetUserByIdResponse() {
        }
        
        public GetUserByIdResponse(TechFixV3._0Client.UserServiceReference.GetUserByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.UserServiceReference.User GetUserByIdResult;
        
        public GetUserByIdResponseBody() {
        }
        
        public GetUserByIdResponseBody(TechFixV3._0Client.UserServiceReference.User GetUserByIdResult) {
            this.GetUserByIdResult = GetUserByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByRoleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByRole", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequestBody Body;
        
        public GetUsersByRoleRequest() {
        }
        
        public GetUsersByRoleRequest(TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersByRoleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string role;
        
        public GetUsersByRoleRequestBody() {
        }
        
        public GetUsersByRoleRequestBody(string role) {
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersByRoleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersByRoleResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponseBody Body;
        
        public GetUsersByRoleResponse() {
        }
        
        public GetUsersByRoleResponse(TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersByRoleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.UserServiceReference.User[] GetUsersByRoleResult;
        
        public GetUsersByRoleResponseBody() {
        }
        
        public GetUsersByRoleResponseBody(TechFixV3._0Client.UserServiceReference.User[] GetUsersByRoleResult) {
            this.GetUsersByRoleResult = GetUsersByRoleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(TechFixV3._0Client.UserServiceReference.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string contactNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username, string password, string role, string name, string location, string contactNumber, string email) {
            this.username = username;
            this.password = password;
            this.role = role;
            this.name = name;
            this.location = location;
            this.contactNumber = contactNumber;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(TechFixV3._0Client.UserServiceReference.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(TechFixV3._0Client.UserServiceReference.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string role;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string contactNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string email;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(int id, string username, string password, string role, string name, string location, string contactNumber, string email) {
            this.id = id;
            this.username = username;
            this.password = password;
            this.role = role;
            this.name = name;
            this.location = location;
            this.contactNumber = contactNumber;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(TechFixV3._0Client.UserServiceReference.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(string UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUser", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.DeleteUserRequestBody Body;
        
        public DeleteUserRequest() {
        }
        
        public DeleteUserRequest(TechFixV3._0Client.UserServiceReference.DeleteUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteUserRequestBody() {
        }
        
        public DeleteUserRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.UserServiceReference.DeleteUserResponseBody Body;
        
        public DeleteUserResponse() {
        }
        
        public DeleteUserResponse(TechFixV3._0Client.UserServiceReference.DeleteUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteUserResult;
        
        public DeleteUserResponseBody() {
        }
        
        public DeleteUserResponseBody(string DeleteUserResult) {
            this.DeleteUserResult = DeleteUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : TechFixV3._0Client.UserServiceReference.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<TechFixV3._0Client.UserServiceReference.UserServiceSoap>, TechFixV3._0Client.UserServiceReference.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.GetUsersResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUsers(TechFixV3._0Client.UserServiceReference.GetUsersRequest request) {
            return base.Channel.GetUsers(request);
        }
        
        public TechFixV3._0Client.UserServiceReference.User[] GetUsers() {
            TechFixV3._0Client.UserServiceReference.GetUsersRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUsersRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUsersRequestBody();
            TechFixV3._0Client.UserServiceReference.GetUsersResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUsers(inValue);
            return retVal.Body.GetUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUsersAsync(TechFixV3._0Client.UserServiceReference.GetUsersRequest request) {
            return base.Channel.GetUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersResponse> GetUsersAsync() {
            TechFixV3._0Client.UserServiceReference.GetUsersRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUsersRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUsersRequestBody();
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.GetUserByIdResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUserById(TechFixV3._0Client.UserServiceReference.GetUserByIdRequest request) {
            return base.Channel.GetUserById(request);
        }
        
        public TechFixV3._0Client.UserServiceReference.User GetUserById(int id) {
            TechFixV3._0Client.UserServiceReference.GetUserByIdRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUserByIdRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUserByIdRequestBody();
            inValue.Body.id = id;
            TechFixV3._0Client.UserServiceReference.GetUserByIdResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUserById(inValue);
            return retVal.Body.GetUserByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUserByIdResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUserByIdAsync(TechFixV3._0Client.UserServiceReference.GetUserByIdRequest request) {
            return base.Channel.GetUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUserByIdResponse> GetUserByIdAsync(int id) {
            TechFixV3._0Client.UserServiceReference.GetUserByIdRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUserByIdRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUserByIdRequestBody();
            inValue.Body.id = id;
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUserByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUsersByRole(TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest request) {
            return base.Channel.GetUsersByRole(request);
        }
        
        public TechFixV3._0Client.UserServiceReference.User[] GetUsersByRole(string role) {
            TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequestBody();
            inValue.Body.role = role;
            TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUsersByRole(inValue);
            return retVal.Body.GetUsersByRoleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.GetUsersByRoleAsync(TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest request) {
            return base.Channel.GetUsersByRoleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.GetUsersByRoleResponse> GetUsersByRoleAsync(string role) {
            TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest inValue = new TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.GetUsersByRoleRequestBody();
            inValue.Body.role = role;
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).GetUsersByRoleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.AddUserResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.AddUser(TechFixV3._0Client.UserServiceReference.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(string username, string password, string role, string name, string location, string contactNumber, string email) {
            TechFixV3._0Client.UserServiceReference.AddUserRequest inValue = new TechFixV3._0Client.UserServiceReference.AddUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            inValue.Body.name = name;
            inValue.Body.location = location;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.email = email;
            TechFixV3._0Client.UserServiceReference.AddUserResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.AddUserResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.AddUserAsync(TechFixV3._0Client.UserServiceReference.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.AddUserResponse> AddUserAsync(string username, string password, string role, string name, string location, string contactNumber, string email) {
            TechFixV3._0Client.UserServiceReference.AddUserRequest inValue = new TechFixV3._0Client.UserServiceReference.AddUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            inValue.Body.name = name;
            inValue.Body.location = location;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.email = email;
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.UpdateUserResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.UpdateUser(TechFixV3._0Client.UserServiceReference.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public string UpdateUser(int id, string username, string password, string role, string name, string location, string contactNumber, string email) {
            TechFixV3._0Client.UserServiceReference.UpdateUserRequest inValue = new TechFixV3._0Client.UserServiceReference.UpdateUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.UpdateUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            inValue.Body.name = name;
            inValue.Body.location = location;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.email = email;
            TechFixV3._0Client.UserServiceReference.UpdateUserResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.UpdateUserResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.UpdateUserAsync(TechFixV3._0Client.UserServiceReference.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.UpdateUserResponse> UpdateUserAsync(int id, string username, string password, string role, string name, string location, string contactNumber, string email) {
            TechFixV3._0Client.UserServiceReference.UpdateUserRequest inValue = new TechFixV3._0Client.UserServiceReference.UpdateUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.UpdateUserRequestBody();
            inValue.Body.id = id;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            inValue.Body.name = name;
            inValue.Body.location = location;
            inValue.Body.contactNumber = contactNumber;
            inValue.Body.email = email;
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.UserServiceReference.DeleteUserResponse TechFixV3._0Client.UserServiceReference.UserServiceSoap.DeleteUser(TechFixV3._0Client.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUser(request);
        }
        
        public string DeleteUser(int id) {
            TechFixV3._0Client.UserServiceReference.DeleteUserRequest inValue = new TechFixV3._0Client.UserServiceReference.DeleteUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.DeleteUserRequestBody();
            inValue.Body.id = id;
            TechFixV3._0Client.UserServiceReference.DeleteUserResponse retVal = ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).DeleteUser(inValue);
            return retVal.Body.DeleteUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.DeleteUserResponse> TechFixV3._0Client.UserServiceReference.UserServiceSoap.DeleteUserAsync(TechFixV3._0Client.UserServiceReference.DeleteUserRequest request) {
            return base.Channel.DeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.UserServiceReference.DeleteUserResponse> DeleteUserAsync(int id) {
            TechFixV3._0Client.UserServiceReference.DeleteUserRequest inValue = new TechFixV3._0Client.UserServiceReference.DeleteUserRequest();
            inValue.Body = new TechFixV3._0Client.UserServiceReference.DeleteUserRequestBody();
            inValue.Body.id = id;
            return ((TechFixV3._0Client.UserServiceReference.UserServiceSoap)(this)).DeleteUserAsync(inValue);
        }
    }
}
