//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechFixV3._0Client.OrdersServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int AdminIdField;
        
        private int SupplierIdField;
        
        private int ItemIdField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        private System.DateTime CreatedAtField;
        
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AdminId {
            get {
                return this.AdminIdField;
            }
            set {
                if ((this.AdminIdField.Equals(value) != true)) {
                    this.AdminIdField = value;
                    this.RaisePropertyChanged("AdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdersServiceReference.OrdersServiceSoap")]
    public interface OrdersServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetOrdersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrders", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse GetOrders(TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse> GetOrdersAsync(TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrdersBySupplierIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySupplierId", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse GetOrdersBySupplierId(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySupplierId", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse> GetOrdersBySupplierIdAsync(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrderByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderById", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse GetOrderById(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderById", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse> GetOrderByIdAsync(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.AddOrderResponse AddOrder(TechFixV3._0Client.OrdersServiceReference.AddOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.AddOrderResponse> AddOrderAsync(TechFixV3._0Client.OrdersServiceReference.AddOrderRequest request);
        
        // CODEGEN: Generating message contract since element name status from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse UpdateOrder(TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse> UpdateOrderAsync(TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse DeleteOrder(TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse> DeleteOrderAsync(TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrders", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrdersRequestBody Body;
        
        public GetOrdersRequest() {
        }
        
        public GetOrdersRequest(TechFixV3._0Client.OrdersServiceReference.GetOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOrdersRequestBody {
        
        public GetOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrdersResponseBody Body;
        
        public GetOrdersResponse() {
        }
        
        public GetOrdersResponse(TechFixV3._0Client.OrdersServiceReference.GetOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.Order[] GetOrdersResult;
        
        public GetOrdersResponseBody() {
        }
        
        public GetOrdersResponseBody(TechFixV3._0Client.OrdersServiceReference.Order[] GetOrdersResult) {
            this.GetOrdersResult = GetOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersBySupplierIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersBySupplierId", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequestBody Body;
        
        public GetOrdersBySupplierIdRequest() {
        }
        
        public GetOrdersBySupplierIdRequest(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersBySupplierIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public GetOrdersBySupplierIdRequestBody() {
        }
        
        public GetOrdersBySupplierIdRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersBySupplierIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersBySupplierIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponseBody Body;
        
        public GetOrdersBySupplierIdResponse() {
        }
        
        public GetOrdersBySupplierIdResponse(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersBySupplierIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.Order[] GetOrdersBySupplierIdResult;
        
        public GetOrdersBySupplierIdResponseBody() {
        }
        
        public GetOrdersBySupplierIdResponseBody(TechFixV3._0Client.OrdersServiceReference.Order[] GetOrdersBySupplierIdResult) {
            this.GetOrdersBySupplierIdResult = GetOrdersBySupplierIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderById", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequestBody Body;
        
        public GetOrderByIdRequest() {
        }
        
        public GetOrderByIdRequest(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public GetOrderByIdRequestBody() {
        }
        
        public GetOrderByIdRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponseBody Body;
        
        public GetOrderByIdResponse() {
        }
        
        public GetOrderByIdResponse(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.Order GetOrderByIdResult;
        
        public GetOrderByIdResponseBody() {
        }
        
        public GetOrderByIdResponseBody(TechFixV3._0Client.OrdersServiceReference.Order GetOrderByIdResult) {
            this.GetOrderByIdResult = GetOrderByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrder", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.AddOrderRequestBody Body;
        
        public AddOrderRequest() {
        }
        
        public AddOrderRequest(TechFixV3._0Client.OrdersServiceReference.AddOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int adminId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int supplierId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int itemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string status;
        
        public AddOrderRequestBody() {
        }
        
        public AddOrderRequestBody(int adminId, int supplierId, int itemId, int quantity, string status) {
            this.adminId = adminId;
            this.supplierId = supplierId;
            this.itemId = itemId;
            this.quantity = quantity;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.AddOrderResponseBody Body;
        
        public AddOrderResponse() {
        }
        
        public AddOrderResponse(TechFixV3._0Client.OrdersServiceReference.AddOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddOrderResult;
        
        public AddOrderResponseBody() {
        }
        
        public AddOrderResponseBody(string AddOrderResult) {
            this.AddOrderResult = AddOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrder", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequestBody Body;
        
        public UpdateOrderRequest() {
        }
        
        public UpdateOrderRequest(TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int adminId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int supplierId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int itemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string status;
        
        public UpdateOrderRequestBody() {
        }
        
        public UpdateOrderRequestBody(int orderId, int adminId, int supplierId, int itemId, int quantity, string status) {
            this.orderId = orderId;
            this.adminId = adminId;
            this.supplierId = supplierId;
            this.itemId = itemId;
            this.quantity = quantity;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponseBody Body;
        
        public UpdateOrderResponse() {
        }
        
        public UpdateOrderResponse(TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateOrderResult;
        
        public UpdateOrderResponseBody() {
        }
        
        public UpdateOrderResponseBody(string UpdateOrderResult) {
            this.UpdateOrderResult = UpdateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrder", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequestBody Body;
        
        public DeleteOrderRequest() {
        }
        
        public DeleteOrderRequest(TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public DeleteOrderRequestBody() {
        }
        
        public DeleteOrderRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponseBody Body;
        
        public DeleteOrderResponse() {
        }
        
        public DeleteOrderResponse(TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteOrderResult;
        
        public DeleteOrderResponseBody() {
        }
        
        public DeleteOrderResponseBody(string DeleteOrderResult) {
            this.DeleteOrderResult = DeleteOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdersServiceSoapChannel : TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdersServiceSoapClient : System.ServiceModel.ClientBase<TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap>, TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap {
        
        public OrdersServiceSoapClient() {
        }
        
        public OrdersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrders(TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest request) {
            return base.Channel.GetOrders(request);
        }
        
        public TechFixV3._0Client.OrdersServiceReference.Order[] GetOrders() {
            TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrdersRequestBody();
            TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrders(inValue);
            return retVal.Body.GetOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrdersAsync(TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest request) {
            return base.Channel.GetOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersResponse> GetOrdersAsync() {
            TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrdersRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrdersRequestBody();
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrdersBySupplierId(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest request) {
            return base.Channel.GetOrdersBySupplierId(request);
        }
        
        public TechFixV3._0Client.OrdersServiceReference.Order[] GetOrdersBySupplierId(int supplierId) {
            TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrdersBySupplierId(inValue);
            return retVal.Body.GetOrdersBySupplierIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrdersBySupplierIdAsync(TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest request) {
            return base.Channel.GetOrdersBySupplierIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdResponse> GetOrdersBySupplierIdAsync(int supplierId) {
            TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrdersBySupplierIdRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrdersBySupplierIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrderById(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest request) {
            return base.Channel.GetOrderById(request);
        }
        
        public TechFixV3._0Client.OrdersServiceReference.Order GetOrderById(int orderId) {
            TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequestBody();
            inValue.Body.orderId = orderId;
            TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrderById(inValue);
            return retVal.Body.GetOrderByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.GetOrderByIdAsync(TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest request) {
            return base.Channel.GetOrderByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.GetOrderByIdResponse> GetOrderByIdAsync(int orderId) {
            TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest inValue = new TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.GetOrderByIdRequestBody();
            inValue.Body.orderId = orderId;
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).GetOrderByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.AddOrderResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.AddOrder(TechFixV3._0Client.OrdersServiceReference.AddOrderRequest request) {
            return base.Channel.AddOrder(request);
        }
        
        public string AddOrder(int adminId, int supplierId, int itemId, int quantity, string status) {
            TechFixV3._0Client.OrdersServiceReference.AddOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.AddOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.AddOrderRequestBody();
            inValue.Body.adminId = adminId;
            inValue.Body.supplierId = supplierId;
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.status = status;
            TechFixV3._0Client.OrdersServiceReference.AddOrderResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).AddOrder(inValue);
            return retVal.Body.AddOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.AddOrderResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.AddOrderAsync(TechFixV3._0Client.OrdersServiceReference.AddOrderRequest request) {
            return base.Channel.AddOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.AddOrderResponse> AddOrderAsync(int adminId, int supplierId, int itemId, int quantity, string status) {
            TechFixV3._0Client.OrdersServiceReference.AddOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.AddOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.AddOrderRequestBody();
            inValue.Body.adminId = adminId;
            inValue.Body.supplierId = supplierId;
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.status = status;
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).AddOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.UpdateOrder(TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest request) {
            return base.Channel.UpdateOrder(request);
        }
        
        public string UpdateOrder(int orderId, int adminId, int supplierId, int itemId, int quantity, string status) {
            TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.adminId = adminId;
            inValue.Body.supplierId = supplierId;
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.status = status;
            TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).UpdateOrder(inValue);
            return retVal.Body.UpdateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.UpdateOrderAsync(TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest request) {
            return base.Channel.UpdateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.UpdateOrderResponse> UpdateOrderAsync(int orderId, int adminId, int supplierId, int itemId, int quantity, string status) {
            TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.UpdateOrderRequestBody();
            inValue.Body.orderId = orderId;
            inValue.Body.adminId = adminId;
            inValue.Body.supplierId = supplierId;
            inValue.Body.itemId = itemId;
            inValue.Body.quantity = quantity;
            inValue.Body.status = status;
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).UpdateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.DeleteOrder(TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest request) {
            return base.Channel.DeleteOrder(request);
        }
        
        public string DeleteOrder(int orderId) {
            TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequestBody();
            inValue.Body.orderId = orderId;
            TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse retVal = ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).DeleteOrder(inValue);
            return retVal.Body.DeleteOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse> TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap.DeleteOrderAsync(TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest request) {
            return base.Channel.DeleteOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechFixV3._0Client.OrdersServiceReference.DeleteOrderResponse> DeleteOrderAsync(int orderId) {
            TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest inValue = new TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequest();
            inValue.Body = new TechFixV3._0Client.OrdersServiceReference.DeleteOrderRequestBody();
            inValue.Body.orderId = orderId;
            return ((TechFixV3._0Client.OrdersServiceReference.OrdersServiceSoap)(this)).DeleteOrderAsync(inValue);
        }
    }
}
